//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openPDCManager.UI.SqlScripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("openPDCManager.UI.SqlScripts.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM OutputStream 
        ///WHERE ID = @outputStreamID;.
        /// </summary>
        internal static string DeleteOutputStream {
            get {
                return ResourceManager.GetString("DeleteOutputStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID, Name
        ///FROM OutputStream
        ///WHERE NodeID = @nodeID
        ///ORDER BY Name;.
        /// </summary>
        internal static string LoadOSLookupList {
            get {
                return ResourceManager.GetString("LoadOSLookupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE OutputStream SET NodeID = @nodeID, 
        ///						Acronym = @acronym,
        ///						Name = @name,
        ///						Type = @type,
        ///						ConnectionString = @connectionString,
        ///						IDCode = @idCode,
        ///						CommandChannel = @commandChannel,
        ///						DataChannel = @dataChannel,
        ///						AutoPublishConfigFrame = @autoPublishConfigFrame,
        ///						AutoStartDataChannel = @autoStartDataChannel,
        ///						NominalFrequncy = @nominalFrequency,
        ///						FramesPerSecond = @framesPerSecond,
        ///						LagTime = @lagTime,
        ///						LeadTime = @leadTime,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaveOutputStream {
            get {
                return ResourceManager.GetString("SaveOutputStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO OutputStream
        ///(
        ///	NodeID, 
        ///	Acronym, 
        ///	Name, 
        ///	Type, 
        ///	ConnectionString, 
        ///	IDCode, 
        ///	CommandChannel, 
        ///	DataChannel,
        ///	AutoPublishConfigFrame, 
        ///	AutoStartDataChannel,
        ///	NominalFrequency,
        ///	FramesPerSecond,
        ///	LagTime,
        ///	LeadTime,
        ///	UseLocalClockAsRealTime,
        ///	AllowSortsByArrival,
        ///	LoadOrder,
        ///	Enabled,
        ///	IgnoreBadTimeStamps,
        ///	TimeResolution,
        ///	AllowPreemptivePublishing,
        ///	DownSamplingMethod,
        ///	DataFormat,
        ///	CoordinateFormat,
        ///	CurrentScalingValue,
        ///	VoltageScalingValue,
        ///	AnalogScalingVal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaveOutputStreamIfNew {
            get {
                return ResourceManager.GetString("SaveOutputStreamIfNew", resourceCulture);
            }
        }
    }
}
